version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_ENV: ${BUILD_ENV}   # 从 workflow 传入
    image: ${DOCKER_USERNAME}/${DOCKER_IMAGE}:${DOCKER_TAG}  # 完全变量化
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=${BUILD_ENV}
