version: "3.8"

services:
  app:
    image: ${DOCKER_USERNAME}/${DOCKER_IMAGE}:${TAG}
    container_name: app
    restart: always
    expose:
      - "3000" # 假设你的应用监听 3000 端口

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
