name: Build and Deploy Frontend

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '9.x'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Set Environment Variables
        env:
        DOCKER_USERNAME_SECRET: ${{ secrets.DOCKER_USERNAME }}
        run: |
         if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
            echo "BUILD_ENV=production" >> $GITHUB_ENV
            echo "TAG=prod" >> $GITHUB_ENV
         else
            echo "BUILD_ENV=development" >> $GITHUB_ENV
            echo "TAG=test" >> $GITHUB_ENV
         fi  # 结束 if

         echo "DOCKER_IMAGE=react-demo" >> $GITHUB_ENV
         echo "DOCKER_USERNAME=$DOCKER_USERNAME_SECRET" >> $GITHUB_ENV
         VERSION=$(jq -r '.version' package.json)
         echo "DOCKER_TAG=$TAG-$VERSION" >> $GITHUB_ENV


      - name: Build and Push Docker Image
        run: |
          echo "Building Docker image $DOCKER_USERNAME/$DOCKER_IMAGE:$DOCKER_TAG"
          docker build --build-arg BUILD_ENV=$BUILD_ENV \
            -t $DOCKER_USERNAME/$DOCKER_IMAGE:$DOCKER_TAG .
          docker push $DOCKER_USERNAME/$DOCKER_IMAGE:$DOCKER_TAG
